a=float(input('Enter 1st number: '))
b=float(input('Enter 2nd number: '))
add= a+b
sub= a-b
mult=a*b
div=a/b
print('Addition=',add)
print('Subtraction=',sub)
print('multiplication=',mult)
print('division=',div)